"""
data/equipment/tiered_kits.py

Loader and selector for the new pre-built full equipment kits
generated by the "set programs" (generate_budget_tiers.py).

These are complete, rule-compliant kits (weapons + layered armor + horse + barding)
organized in 10 wealth tiers matching the starting capital scale.

Best strategy integration:
- Use these as the *primary* source of equipment for characters.
- Selection (updated rule):
  - The tier/file chosen is the one whose range *contains* the starting capital.
    Examples: 150 sp → 101-200sp ; 543 sp → 401-700sp.
  - Then, inside that tier/file, choose the set whose cost ([Nsp] value listed
    in the file, e.g. [142sp]) is the *closest* to the character's starting capital.
    Tie-break: prefer <= capital (no overspend) when distances equal.
    No random, no higher tier.
- Decompose the chosen kit into the existing Phase1/2/3 columns for compatibility.
- Fall back to the old phased system (weapon_kits + armor_sets + remaining_equipment)
  only for very poor characters where no good prebuilt kit fits.

The compact .txt files are easy to parse and contain the full item list for a kit.
"""

from pathlib import Path
from typing import List, Dict, Optional, Tuple
import re

BASE_DIR = Path(__file__).parent
SETS_DIR = BASE_DIR / "systeme armure preconstruites" / "sets_by_budget"

# Tier definitions matching the generated files (min, max, filename stem)
TIER_DEFINITIONS: List[Tuple[int, int, str]] = [
    (1, 20, "sets_001-020sp"),
    (21, 50, "sets_021-050sp"),
    (51, 100, "sets_051-100sp"),
    (101, 200, "sets_101-200sp"),
    (201, 400, "sets_201-400sp"),
    (401, 700, "sets_401-700sp"),
    (701, 1100, "sets_701-1100sp"),
    (1101, 1500, "sets_1101-1500sp"),
    (1501, 1800, "sets_1501-1800sp"),
    (1801, 2200, "sets_1801-2200sp"),
]

# Rough categorization keywords (extend as needed)
WEAPON_KEYWORDS = {
    "sword", "axe", "mace", "hammer", "lance", "spear", "halberd", "poleaxe",
    "glaive", "bill", "pike", "lucerne", "guisarme", "billhook", "flail",
    "messer", "baselard", "falchion", "cutlass", "katzbalger", "broadsword",
    "scimitar", "rapier", "sidesword", "main-gauche", "estoc", "longsword",
    "bastard", "quarterstaff", "maul", "war hammer", "morning star",
    "bow", "crossbow", "sling", "javelin", "dart", "francisca", "hand axe",
    "club", "staff sling", "war dart", "reinforced javelin"
}

SHIELD_KEYWORDS = {"shield", "buckler", "rotella", "brocchiere", "heater", "kite", "scutum", "parma"}

MOUNT_KEYWORDS = {
    "destrier", "palfrey", "courser", "rouncey", "pony", "mule",
    "saddle", "barding", "chanfron", "crinet"
}

ARMOR_KEYWORDS = {
    "breastplate", "brigandine", "hauberk", "haubergeon", "mail shirt",
    "mail coat", "jack of plates", "coat of plates", "gambeson", "aketon",
    "pourpoint", "arming doublet", "padded jack", "simple breastplate",
    "helmet", "cervelière", "kettle hat", "sallet", "armet", "burgonet",
    "bascinet", "morion", "cabasset", "close helmet", "great helm",
    "great bascinet", "lobster", "nasal", "barbute",
    "gorget", "bevor", "pauldrons", "besagews", "vambraces", "couter",
    "rerebrace", "gauntlets", "fauld", "plackart", "garde-reins",
    "tassets", "cuisses", "poleyns", "greaves", "schynbalds", "sabatons",
    "aventail", "mail coif", "mail voiders", "mail chausses", "mail demi-chausses",
    "underlayer", "gambeson", "reinforced gambeson"
}


def _get_tier_file(min_budget: int, max_budget: int) -> Optional[Path]:
    for tmin, tmax, stem in TIER_DEFINITIONS:
        if tmin == min_budget and tmax == max_budget:
            return SETS_DIR / f"{stem}.txt"
    return None


def load_all_tiers() -> Dict[Tuple[int, int], List[Dict]]:
    """
    Load all tier sets into memory.
    Returns: {(1,20): [ {"budget": 5, "items": ["Sling", "Leather Helmet"], "cost_sp": 5}, ... ], ... }
    """
    tiers: Dict[Tuple[int, int], List[Dict]] = {}
    for minb, maxb, stem in TIER_DEFINITIONS:
        path = SETS_DIR / f"{stem}.txt"
        if not path.exists():
            continue
        sets = []
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line.startswith("#"):
                    continue
                # Format: #001 [12sp] Item1, Item2, ...
                m = re.search(r"\[(\d+)sp\]\s*(.+)", line)
                if not m:
                    continue
                budget = int(m.group(1))
                items_str = m.group(2).strip()
                items = [item.strip() for item in items_str.split(",") if item.strip()]
                sets.append({
                    "budget": budget,
                    "items": items,
                    "cost_sp": budget,  # approximate; the [] value is the generation budget
                    "raw": line
                })
        if sets:
            tiers[(minb, maxb)] = sets
    return tiers


# Cache
_ALL_TIERS: Optional[Dict[Tuple[int, int], List[Dict]]] = None


def get_all_tiers() -> Dict[Tuple[int, int], List[Dict]]:
    global _ALL_TIERS
    if _ALL_TIERS is None:
        _ALL_TIERS = load_all_tiers()
    return _ALL_TIERS


def get_tier_for_capital(capital_sp: float) -> Optional[Tuple[int, int]]:
    """Return the tier whose range *contains* the starting capital.

    Rule (user upgrade):
      - The equipment file (tier) chosen is the one that contains the capital.
      - Example: starting capital 150 sp  → sets_101-200sp.txt   (101 <= 150 <= 200)
      - Example: starting capital 543 sp  → sets_401-700sp.txt   (401 <= 543 <= 700)

    Implementation:
      - Find (tmin, tmax) such that tmin <= capital_sp <= tmax.
      - Exact upper boundaries belong to that tier (200 → 101-200, 400 → 201-400, etc.).
      - If capital below the lowest tier: use lowest.
      - If capital above the highest tier: use highest.

    Then: inside the chosen tier/file, pick the set whose [Nsp] cost is closest
    to the actual starting capital (see select_prebuilt_kit for exact closest logic
    + tie-breaker preferring not to overspend).
    """
    if capital_sp <= 0:
        capital_sp = 1.0

    # Use the authoritative TIER_DEFINITIONS (sorted and contiguous)
    for tmin, tmax, _stem in TIER_DEFINITIONS:
        if tmin <= capital_sp <= tmax:
            return (tmin, tmax)

    # Fallbacks (shouldn't normally be reached for valid capitals)
    if capital_sp > TIER_DEFINITIONS[-1][1]:
        last = TIER_DEFINITIONS[-1]
        return (last[0], last[1])
    # below lowest
    first = TIER_DEFINITIONS[0]
    return (first[0], first[1])


def select_prebuilt_kit(capital_sp: float) -> Optional[Dict]:
    """
    Main entry point.

    Selection strategy:
    - Identify the tier whose range *contains* the starting capital
      (user rule: "le fichier d'equipement choisi est celui qui contient le starting capital").
      Examples given: 150 sp → (101,200), 543 sp → (401,700).
    - Then, inside that file, select the set whose "budget" ([Nsp] cost) is
      closest to the starting capital (min abs diff). Tie-break: prefer the
      set with cost <= capital when distances are equal. No randomness,
      no leakage to other tiers.

    Returns a dict with:
      - tier: (min, max)
      - kit: the chosen set dict (with 'items', 'budget'...)
      - categorized: { 'weapons': [...], 'armor': [...], 'mount': [...], 'other': [...] }
      - total_cost_sp: the budget of the chosen set (used for spend calc)
    """
    tiers = get_all_tiers()
    if not tiers:
        return None

    tier = get_tier_for_capital(capital_sp)
    if tier is None:
        tier = min(tiers.keys())

    candidates = tiers.get(tier, [])
    if not candidates:
        # try lower tiers (shouldn't be needed with new get_tier logic, but kept for safety)
        for t in sorted(tiers.keys()):
            if t[1] <= tier[0]:
                candidates = tiers[t]
                tier = t
                break

    if not candidates:
        return None

    # NEW RULE (user upgrade): once the tier file is selected (the one containing the capital),
    # choose the set whose "budget" (the [Nsp] cost shown in the file) is *closest* to the
    # character's starting capital.
    # - Pure numeric distance: min( |set_budget - capital_sp| )
    # - Tie-breaker: if two sets are equally distant (e.g. 140 and 160 for 150sp), prefer
    #   the one that does not exceed the capital (keeps more pocket money).
    # - If still tied, prefer the higher budget (richer kit).
    def _closest_key(s):
        b = s["budget"]
        diff = abs(b - capital_sp)
        overspend = 0 if b <= capital_sp else 1
        return (diff, overspend, -b)  # smallest diff, then no-overspend, then largest b

    chosen = min(candidates, key=_closest_key)

    categorized = _categorize_items(chosen["items"])

    return {
        "tier": tier,
        "tier_name": f"{tier[0]}-{tier[1]}sp",
        "kit": chosen,
        "items": chosen["items"],
        "categorized": categorized,
        "total_cost_sp": chosen["budget"],
        "source": "prebuilt_tiered_kit"
    }


def _categorize_items(items: List[str]) -> Dict[str, List[str]]:
    """Split items into rough categories for the 3-phase columns.
    Priority: mount > weapon/shield > armor > other (remaining goes to pocket/phase3 rest).
    """
    weapons = []
    armor = []
    mount = []
    other = []

    ammo_re = re.compile(r'^(.+?) \((\d+)\)$')
    for item in items:
        # Ammo packs must go to "other" (will be consolidated later and end up in Monture_et_Reste).
        # This prevents misclassification e.g. "Sling bullets (12)" matching WEAPON_KEYWORDS["sling"]
        # or "Crossbow Bolts (12)" matching "crossbow", which was causing ammo to pollute Armes_et_Bouclier.
        if ammo_re.match(item):
            other.append(item)
            continue

        lower = item.lower()
        is_mount = any(kw in lower for kw in MOUNT_KEYWORDS)
        is_weapon_or_shield = any(kw in lower for kw in WEAPON_KEYWORDS) or any(kw in lower for kw in SHIELD_KEYWORDS)
        is_armor = any(kw in lower for kw in ARMOR_KEYWORDS)

        if is_mount:
            mount.append(item)
        elif is_weapon_or_shield:
            weapons.append(item)
        elif is_armor:
            armor.append(item)
        else:
            other.append(item)

    return {
        "weapons_and_shield": weapons,
        "armor": armor,
        "mount_and_horse": mount,
        "other": other
    }


def consolidate_ammo(items: List[str]) -> List[str]:
    """Merge accumulated ammunition of the same type into a single entry by summing quantities.

    E.g. ["Sling bullets (12)", "Sling bullets (12)", "Sling bullets (12)", "Sling bullets (12)"]
    becomes ["Sling bullets (48)"].

    Non-ammo items are kept (in original order). Consolidated ammo entries are appended
    after the non-ammo items, in the order their ammo type was first encountered.

    Ammo are detected as strings ending with " (N)" where N is integer (e.g. Arrows (12),
    Crossbow Bolts (24), Heavy Crossbow Bolts (9), Sling bullets (48), ...).

    This is applied when building the CSV display columns (Armes_et_Bouclier, Monture_et_Reste etc.)
    so that repeated packs don't pollute the columns with duplicates.
    """
    if not items:
        return []
    ammo_re = re.compile(r'^(.+?) \((\d+)\)$')
    ammo_order = []
    ammo_totals = {}
    non_ammo = []
    for item in items:
        m = ammo_re.match(item)
        if m:
            base = m.group(1).strip()
            qty = int(m.group(2))
            if base not in ammo_totals:
                ammo_order.append(base)
            ammo_totals[base] = ammo_totals.get(base, 0) + qty
        else:
            non_ammo.append(item)
    consolidated_ammo = [f"{base} ({ammo_totals[base]})" for base in ammo_order]
    return non_ammo + consolidated_ammo


def format_for_phases(kit_result: Dict) -> Dict:
    """
    Convert a prebuilt kit into the fields the current generator expects
    for the 3 phases and CSV columns.
    """
    cat = kit_result["categorized"]
    items = kit_result["items"]

    armes = ", ".join(cat["weapons_and_shield"]) if cat["weapons_and_shield"] else "Aucun"
    armure = ", ".join(cat["armor"]) if cat["armor"] else "Aucune"
    monture = ", ".join(cat["mount_and_horse"]) if cat["mount_and_horse"] else ""

    # Put any uncategorized "other" items into the remaining/mount column
    # (they will appear as part of "Monture_et_Reste" or pocket money logic)
    # Ammo of same type are consolidated (e.g. four "Sling bullets (12)" -> "Sling bullets (48)")
    if cat["other"]:
        other_cons = consolidate_ammo(cat["other"])
        extra = ", ".join(other_cons)
        if monture:
            monture = monture + " + " + extra
        else:
            monture = extra

    if not monture:
        monture = "Aucun"

    return {
        "Phase1_Weapon_Kit": armes,
        "Phase2_Armor_Set": armure if cat["armor"] else "Aucune",
        "Phase3_Mount": monture,
        "Armes_et_Bouclier": armes,
        "Armure": armure if cat["armor"] else "Aucune",
        "Monture_et_Reste": monture,
        "Prebuilt_Kit_Items": items,
        "Prebuilt_Kit_Tier": kit_result["tier_name"],
        "Prebuilt_Kit_Cost_Sp": kit_result.get("total_cost_sp", kit_result["kit"]["budget"]),
    }


if __name__ == "__main__":
    # Quick self-test
    print("Loading tiered kits...")
    tiers = get_all_tiers()
    print(f"Loaded {len(tiers)} tiers")

    # Test capitals including user's explicit examples for the "containing tier" rule
    for capital in [15, 75, 150, 180, 543, 450, 950, 1600, 2100]:
        kit = select_prebuilt_kit(capital)
        if kit:
            phases = format_for_phases(kit)
            delta = kit['total_cost_sp'] - capital
            print(f"\nCapital {capital}sp -> Tier {kit['tier_name']}")
            print(f"  Chosen set cost ~{kit['total_cost_sp']}sp (delta {delta:+.0f}sp vs capital)")
            print(f"  Weapons: {phases['Armes_et_Bouclier'][:80]}...")
            print(f"  Armor  : {phases['Armure'][:60]}...")
            print(f"  Mount  : {phases['Monture_et_Reste'][:60]}...")
        else:
            print(f"Capital {capital}sp -> no kit found")