# race_data.py - Statistiques des ethnies (Version Finale Corrigée)

ethnicity_data = {
    # ==================== HUMAINS ====================
    "Calishites":      {"idx": 1,  "r": "Humain", "w": -2, "b": 2,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 0, "vig": 0, "bea": 1, "spec": "Aucun", "cp": 0},
    "Chondathans":     {"idx": 2,  "r": "Humain", "w": 0,  "b": 0,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 0, "reg": 0, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Damarans":        {"idx": 3,  "r": "Humain", "w": 1,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 1, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Illuskans":       {"idx": 4,  "r": "Humain", "w": 2,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 1, "vig": 1, "bea": 0, "spec": "Aucun", "cp": 0},
    "Mulan":           {"idx": 5,  "r": "Humain", "w": -1, "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 0, "reg": 0, "vig": 1, "bea": 1, "spec": "Aucun", "cp": 0},
    "Rashemi":         {"idx": 6,  "r": "Humain", "w": 1,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 1, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Tethyrians":      {"idx": 7,  "r": "Humain", "w": 0,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 0, "reg": 0, "vig": 0, "bea": 1, "spec": "Aucun", "cp": 0},
    "Chultan":         {"idx": 8,  "r": "Humain", "w": 2,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 2, "reg": 2, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Turami":          {"idx": 9,  "r": "Humain", "w": 1,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 1, "vig": 0, "bea": 1, "spec": "Aucun", "cp": 0},
    "Ffolk":           {"idx": 10, "r": "Humain", "w": 1,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 0, "vig": 0, "bea": 1, "spec": "Aucun", "cp": 0},
    "Sossrim":         {"idx": 11, "r": "Humain", "w": 2,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 1, "vig": 1, "bea": 0, "spec": "Aucun", "cp": 0},
    "Arkaiuns":        {"idx": 123,"r": "Humain", "w": 1,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 0, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Durpari":         {"idx": 124,"r": "Humain", "w": 0,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 1, "vig": 0, "bea": 1, "spec": "Aucun", "cp": 0},
    "Gûr":             {"idx": 125,"r": "Humain", "w": 1,  "b": 2,  "bal": 0, "spd": 1, "coo": 0, "pre": 0, "end": 2, "reg": 1, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Halruéens":       {"idx": 126,"r": "Humain", "w": -1, "b": 0,  "bal": 1, "spd": 0, "coo": 1, "pre": 2, "end": 0, "reg": 0, "vig": 1, "bea": 1, "spec": "Aucun", "cp": 0},
    "Imaskari":        {"idx": 127,"r": "Humain", "w": 0,  "b": 1,  "bal": 0, "spd": 0, "coo": 1, "pre": 1, "end": 1, "reg": 1, "vig": 1, "bea": 0, "spec": "Aucun", "cp": 0},
    "Lantannas":       {"idx": 128,"r": "Humain", "w": 0,  "b": 0,  "bal": 0, "spd": 0, "coo": 1, "pre": 1, "end": 0, "reg": 0, "vig": 1, "bea": 1, "spec": "Aucun", "cp": 0},
    "Lapalis":         {"idx": 129,"r": "Humain", "w": 1,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 0, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Nar":             {"idx": 130,"r": "Humain", "w": 2,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 1, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Raumviriens":     {"idx": 131,"r": "Humain", "w": 1,  "b": 1,  "bal": 0, "spd": 0, "coo": 0, "pre": 0, "end": 1, "reg": 0, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Shaaryens":       {"idx": 132,"r": "Humain", "w": 2,  "b": 2,  "bal": 0, "spd": 1, "coo": 0, "pre": 0, "end": 2, "reg": 1, "vig": 0, "bea": 0, "spec": "Aucun", "cp": 0},
    "Tashaliens":      {"idx": 133,"r": "Humain", "w": 0,  "b": 1,  "bal": 0, "spd": 0, "coo": 1, "pre": 1, "end": 1, "reg": 0, "vig": 1, "bea": 1, "spec": "Aucun", "cp": 0},
    "Uthgardt":        {"idx": 138,"r": "Humain", "w": 3,  "b": 2,  "bal": 0, "spd": 1, "coo": 0, "pre": 0, "end": 3, "reg": 3, "vig": 0, "bea": -1, "spec": "Aucun", "cp": 0.6},

    # ==================== HALFLINGS ====================
    "Strongheart":     {"idx": 12, "r": "Halfelin", "w": -13, "b": 2, "bal": 2, "spd": 1, "coo": 1, "pre": 1, "end": 2, "reg": 2, "vig": 1, "bea": 0, "spec": "Robustesse halfeline", "cp": 0},
    "Lightfoot":       {"idx": 13, "r": "Halfelin", "w": -13, "b": 2, "bal": 2, "spd": 2, "coo": 2, "pre": 1, "end": 1, "reg": 0, "vig": 2, "bea": 2, "spec": "Furtivité naturelle", "cp": 0},
    "Ghostwalk":       {"idx": 14, "r": "Halfelin", "w": -13, "b": 2, "bal": 3, "spd": 2, "coo": 1, "pre": 2, "end": 1, "reg": 1, "vig": 3, "bea": 1, "spec": "Télépathie silencieuse", "cp": 0.8},
    "Tallfellow":      {"idx": 117,"r": "Halfelin", "w": -13, "b": 1, "bal": 1, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 0, "vig": 2, "bea": 2, "spec": "Furtivité naturelle", "cp": 0},

    # ==================== NAINS ====================
    "Nain d'écu":      {"idx": 15, "r": "Nain", "w": 3,  "b": 19, "bal": -2, "spd": -1, "coo": 0, "pre": 0, "end": 3, "reg": 4, "vig": 1, "bea": -2, "spec": "Vision dans le noir (Darkvision N1) + robustesse naine", "cp": 2},
    "Nain d'or":       {"idx": 16, "r": "Nain", "w": 4,  "b": 20, "bal": -2, "spd": -1, "coo": 0, "pre": 0, "end": 3, "reg": 4, "vig": 1, "bea": -1, "spec": "Vision dans le noir (Darkvision N1) + robustesse naine", "cp": 2},
    "Nain gris":       {"idx": 17, "r": "Nain", "w": 3,  "b": 19, "bal": -2, "spd": -1, "coo": 0, "pre": 0, "end": 3, "reg": 4, "vig": 1, "bea": -2, "spec": "Invisibilité + Agrandissement", "cp": 2},
    "Nain arctique":   {"idx": 18, "r": "Nain", "w": 3,  "b": 18, "bal": -2, "spd": -2, "coo": 0, "pre": 0, "end": 3, "reg": 5, "vig": 1, "bea": -2, "spec": "Vision dans le noir (Darkvision N1) + robustesse naine", "cp": 2},
    "Nain sauvages":   {"idx": 19, "r": "Nain", "w": 4,  "b": 17, "bal": -2, "spd": 0,  "coo": 0, "pre": 0, "end": 2, "reg": 3, "vig": 0, "bea": -1, "spec": "Vision dans le noir (Darkvision N1) + robustesse naine", "cp": 2},
    "Urdunnir":        {"idx": 20, "r": "Nain", "w": 5,  "b": 22, "bal": -2, "spd": -1, "coo": -1, "pre": 0, "end": 3, "reg": 4, "vig": 1, "bea": -2, "spec": "Marche à travers la pierre", "cp": 2},

    # ==================== DEMI-ELFES ====================
    "Demi-elfe des bois":    {"idx": 21, "r": "Demi-elfe", "w": -3, "b": 1, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 1, "reg": 1, "vig": 2, "bea": 2, "spec": "Méditation + Immunité au sommeil + Vision nocturne (N1)", "cp": 2.0},
    "Demi-elfe de la lune":  {"idx": 22, "r": "Demi-elfe", "w": -3, "b": 1, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 0, "reg": 1, "vig": 2, "bea": 3, "spec": "Méditation + Immunité au sommeil + Vision nocturne (N1)", "cp": 2.0},
    "Demi-elfe noir":        {"idx": 23, "r": "Demi-elfe", "w": -4, "b": 1, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 1, "reg": 1, "vig": 2, "bea": 1, "spec": "Méditation + Immunité au sommeil + Vision dans le noir (N1) + Sorts innés (N1)", "cp": 3.0},
    "Demi-elfe du soleil":   {"idx": 24, "r": "Demi-elfe", "w": -3, "b": 1, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 0, "reg": 1, "vig": 2, "bea": 3, "spec": "Méditation + Immunité au sommeil + Vision nocturne (N1)", "cp": 2.0},
    "Demi-elfe sauvage":     {"idx": 25, "r": "Demi-elfe", "w": -3, "b": 1, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 1, "reg": 2, "vig": 1, "bea": 1, "spec": "Méditation + Immunité au sommeil + Vision nocturne (N1)", "cp": 2.0},
    "Demi-elfe de la mer":   {"idx": 26, "r": "Demi-elfe", "w": -2, "b": 1, "bal": 2, "spd": 1, "coo": 1, "pre": 1, "end": 2, "reg": 2, "vig": 2, "bea": 2, "spec": "Respiration aquatique + Méditation + Immunité au sommeil + Vision nocturne (N1)", "cp": 2.5},
    "Demi-elfe des étoiles": {"idx": 27, "r": "Demi-elfe", "w": -3, "b": 0, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 0, "reg": 1, "vig": 3, "bea": 4, "spec": "Magie stellaire innée + Méditation + Immunité au sommeil + Vision nocturne (N1)", "cp": 2.0},
    "Demi-avariel":          {"idx": 28, "r": "Demi-elfe", "w": -4, "b": 1, "bal": 2, "spd": 1, "coo": 1, "pre": 1, "end": -1, "reg": 0, "vig": 2, "bea": 3, "spec": "Vol naturel + Méditation + Immunité au sommeil + Vision nocturne (N1)", "cp": 4.5},
    "Demi-lythari":          {"idx": 29, "r": "Demi-elfe", "w": -3, "b": 0, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 1, "reg": 2, "vig": 2, "bea": 2, "spec": "Lycanthropie lupine contrôlée + Méditation + Immunité au sommeil + Vision nocturne (N1)", "cp": 2.2},

    # ==================== ELFES ====================
    "Elfe des bois":     {"idx": 30, "r": "Elfe", "w": -3, "b": 0,  "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 1, "vig": 2, "bea": 2, "spec": "Transe + Méditation + Immunité au sommeil + Vision nocturne (N2)", "cp": 3.0},
    "Elfe de la lune":   {"idx": 31, "r": "Elfe", "w": -4, "b": -1, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 0, "reg": 1, "vig": 2, "bea": 3, "spec": "Transe + Méditation + Immunité au sommeil + Vision nocturne (N2)", "cp": 3.0},
    "Elfe noir":         {"idx": 32, "r": "Elfe", "w": -5, "b": 0,  "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 1, "vig": 2, "bea": 1, "spec": "Sorts innés (N2) + Méditation + Immunité au sommeil + Darkvision (N2)", "cp": 5.0},
    "Elfe du soleil":    {"idx": 33, "r": "Elfe", "w": -2, "b": 0,  "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 0, "reg": 1, "vig": 2, "bea": 3, "spec": "Transe + Méditation + Immunité au sommeil + Vision nocturne (N2)", "cp": 3.0},
    "Elfe sauvage":      {"idx": 34, "r": "Elfe", "w": -3, "b": 0,  "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 2, "vig": 1, "bea": 1, "spec": "Transe + Méditation + Immunité au sommeil + Vision nocturne (N2)", "cp": 3.0},
    "Elfe de la mer":    {"idx": 35, "r": "Elfe", "w": -2, "b": 0,  "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 2, "reg": 2, "vig": 2, "bea": 2, "spec": "Respiration aquatique + Transe + Méditation + Immunité au sommeil + Vision nocturne (N2)", "cp": 3.5},
    "Elfe des étoiles":  {"idx": 36, "r": "Elfe", "w": -2, "b": -1, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": -1, "reg": 1, "vig": 3, "bea": 4, "spec": "Magie stellaire innée + Transe + Méditation + Immunité au sommeil + Vision nocturne (N2)", "cp": 3.0},
    "Avariel":           {"idx": 37, "r": "Elfe", "w": -4, "b": 0,  "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": -1, "reg": 0, "vig": 2, "bea": 3, "spec": "Vol naturel + Transe + Méditation + Immunité au sommeil + Vision nocturne (N2)", "cp": 5.5},
    "Lythari":           {"idx": 38, "r": "Elfe", "w": -3, "b": -1, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 2, "vig": 2, "bea": 2, "spec": "Lycanthropie lupine contrôlée + Transe + Méditation + Immunité au sommeil + Vision nocturne (N2)", "cp": 3.8},

    # ==================== GNOMES ====================
    "Gnome des roches":     {"idx": 39, "r": "Gnome", "w": -10, "b": 4, "bal": 1, "spd": 1, "coo": 2, "pre": 3, "end": 2, "reg": 3, "vig": 1, "bea": -1, "spec": "Affinité illusion", "cp": 0},
    "Gnome des forêts":     {"idx": 40, "r": "Gnome", "w": -10, "b": 4, "bal": 2, "spd": 2, "coo": 3, "pre": 2, "end": 1, "reg": 1, "vig": 2, "bea": 1, "spec": "Affinité nature", "cp": 0},
    "Gnome des profondeurs":{"idx": 41, "r": "Gnome", "w": -10, "b": 5, "bal": 1, "spd": 1, "coo": 2, "pre": 3, "end": 2, "reg": 4, "vig": 1, "bea": -2, "spec": "Camouflage pierre", "cp": 1.0},
    "Deep Gnome":           {"idx": 68, "r": "Gnome", "w": -10, "b": 5, "bal": 1, "spd": 1, "coo": 2, "pre": 3, "end": 2, "reg": 4, "vig": 1, "bea": -2, "spec": "Camouflage pierre", "cp": 1.0},

    # ==================== DEMI-ORCS & ORCS ====================
    "Mountain Orc":  {"idx": 42, "r": "Demi-orc", "w": 2, "b": 2, "bal": 0, "spd": 1, "coo": 0, "pre": -1, "end": 2, "reg": 2, "vig": 0, "bea": -2, "spec": "Aucun", "cp": 0},
    "Gray Orc":      {"idx": 43, "r": "Demi-orc", "w": 2, "b": 2, "bal": 0, "spd": 1, "coo": 0, "pre": -1, "end": 2, "reg": 2, "vig": 0, "bea": -2, "spec": "Aucun", "cp": 0},
    "Orogs":         {"idx": 44, "r": "Demi-orc", "w": 3, "b": 3, "bal": 0, "spd": 1, "coo": -1, "pre": -1, "end": 2, "reg": 2, "vig": 0, "bea": -3, "spec": "Aucun", "cp": 0},
    "Orc":           {"idx": 100,"r": "Autre",    "w": 4, "b": 2, "bal": -1, "spd": 1, "coo": -1, "pre": -1, "end": 2, "reg": 2, "vig": 0, "bea": -3, "spec": "Furie orque", "cp": 0},




       # ==================== AUTRES RACES (48 à 137) ====================
    "Drakeide":         {"idx": 48, "r": "Autre", "w": 4, "b": 2, "bal": 1, "spd": 1, "coo": 0, "pre": 0, "end": 2, "reg": 3, "vig": 1, "bea": 0, "spec": "Souffle élémentaire", "cp": 1.5},
    "Protector Aasimar":{"idx": 49, "r": "Autre", "w": 0, "b": 0, "bal": 1, "spd": 1, "coo": 1, "pre": 2, "end": 1, "reg": 2, "vig": 2, "bea": 3, "spec": "Lumière sacrée", "cp": 1.8},
    "Scourge Aasimar":  {"idx": 50, "r": "Autre", "w": 0, "b": 0, "bal": 1, "spd": 1, "coo": 1, "pre": 2, "end": 2, "reg": 1, "vig": 2, "bea": 2, "spec": "Radiance consumante", "cp": 2.0},
    "Fallen Aasimar":   {"idx": 51, "r": "Autre", "w": 0, "b": 0, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 1, "reg": 2, "vig": 1, "bea": 1, "spec": "Lumière sombre", "cp": 1.8},
    "Goliath":          {"idx": 52, "r": "Autre", "w": 8, "b": 0, "bal": 1, "spd": 0, "coo": -1, "pre": -1, "end": 3, "reg": 4, "vig": 0, "bea": -2, "spec": "Réduction de dégâts", "cp": 1.5},
    "Genasi Terre":     {"idx": 53, "r": "Autre", "w": 3, "b": 3, "bal": 0, "spd": -1, "coo": 0, "pre": 1, "end": 3, "reg": 2, "vig": 1, "bea": -1, "spec": "Affinité terre", "cp": 1.2},
    "Genasi Feu":       {"idx": 54, "r": "Autre", "w": 1, "b": 2, "bal": 1, "spd": 2, "coo": 1, "pre": 1, "end": 2, "reg": 1, "vig": 2, "bea": 1, "spec": "Affinité feu", "cp": 1.5},
    "Genasi Air":       {"idx": 55, "r": "Autre", "w": -2, "b": 0, "bal": 2, "spd": 4, "coo": 2, "pre": 2, "end": 1, "reg": 0, "vig": 3, "bea": 2, "spec": "Affinité air", "cp": 1.8},
    "Genasi Eau":       {"idx": 56, "r": "Autre", "w": 1, "b": 1, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 3, "reg": 3, "vig": 1, "bea": 1, "spec": "Affinité eau", "cp": 1.3},
    "Firbolg":          {"idx": 57, "r": "Autre", "w": 6, "b": 4, "bal": 1, "spd": 0, "coo": 0, "pre": 0, "end": 3, "reg": 3, "vig": 1, "bea": 0, "spec": "Magie druidique innée", "cp": 1.4},
    "Tabaxi":           {"idx": 58, "r": "Autre", "w": -4, "b": 0, "bal": 3, "spd": 4, "coo": 2, "pre": 2, "end": 1, "reg": 1, "vig": 2, "bea": 1, "spec": "Agilité féline", "cp": 1.3},
    "Forgelier":        {"idx": 59, "r": "Autre", "w": 7, "b": 8, "bal": 2, "spd": 0, "coo": 0, "pre": 1, "end": 4, "reg": 3, "vig": 1, "bea": -2, "spec": "Corps construct", "cp": 1.6},
    "Aarakocra":        {"idx": 60, "r": "Autre", "w": -6, "b": 0, "bal": 2, "spd": 4, "coo": 1, "pre": 1, "end": 1, "reg": 0, "vig": 3, "bea": 2, "spec": "Vol naturel très puissant", "cp": 3.0},
    "Abbalaya":         {"idx": 61, "r": "Autre", "w": -1, "b": 1, "bal": 1, "spd": 2, "coo": 2, "pre": 2, "end": 2, "reg": 1, "vig": 2, "bea": 1, "spec": "Aucun", "cp": 0.8},
    "Alaghi":           {"idx": 62, "r": "Autre", "w": 6, "b": 4, "bal": 0, "spd": 1, "coo": -1, "pre": -1, "end": 3, "reg": 2, "vig": 0, "bea": -2, "spec": "Force brute", "cp": 1.2},
    "Aranea":           {"idx": 63, "r": "Autre", "w": -4, "b": -2, "bal": 2, "spd": 2, "coo": 3, "pre": 3, "end": 1, "reg": 0, "vig": 2, "bea": 2, "spec": "Métamorphose araignée", "cp": 1.5},
    "Bullywug":         {"idx": 64, "r": "Autre", "w": -6, "b": 0, "bal": 2, "spd": 2, "coo": -1, "pre": -1, "end": 2, "reg": 2, "vig": 0, "bea": -2, "spec": "Saut puissant", "cp": 0.8},
    "Caiman Katanga":   {"idx": 65, "r": "Autre", "w": 4, "b": 3, "bal": 1, "spd": 1, "coo": 0, "pre": 0, "end": 3, "reg": 3, "vig": 1, "bea": -1, "spec": "Forme caïman", "cp": 1.0},
    "Centaur":          {"idx": 66, "r": "Autre", "w": 5, "b": 3, "bal": 1, "spd": 3, "coo": 0, "pre": 0, "end": 3, "reg": 2, "vig": 1, "bea": 0, "spec": "Charge puissante", "cp": 1.2},
    "Chitine":          {"idx": 67, "r": "Autre", "w": -6, "b": 2, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 1, "vig": 2, "bea": -2, "spec": "Toile + griffes", "cp": 1.2},
    "Deep Gnome":       {"idx": 68, "r": "Gnome", "w": -10, "b": 5, "bal": 1, "spd": 1, "coo": 2, "pre": 3, "end": 2, "reg": 4, "vig": 1, "bea": -2, "spec": "Camouflage pierre", "cp": 1.0},
    "Elan":             {"idx": 69, "r": "Autre", "w": -2, "b": 0, "bal": 2, "spd": 1, "coo": 2, "pre": 2, "end": 1, "reg": 1, "vig": 3, "bea": 2, "spec": "Pouvoirs psioniques", "cp": 1.8},
    "Firenewt":         {"idx": 70, "r": "Autre", "w": 2, "b": 3, "bal": 1, "spd": 1, "coo": 0, "pre": 0, "end": 3, "reg": 4, "vig": 1, "bea": -2, "spec": "Résistance feu", "cp": 1.2},
    "Fremlin":          {"idx": 71, "r": "Autre", "w": -17, "b": 0, "bal": 3, "spd": 3, "coo": 3, "pre": 2, "end": -1, "reg": -2, "vig": 2, "bea": -3, "spec": "Sabotage + Furtivité", "cp": 0.5},
    "Githzerai":        {"idx": 72, "r": "Autre", "w": -1, "b": 0, "bal": 2, "spd": 1, "coo": 1, "pre": 1, "end": 1, "reg": 1, "vig": 2, "bea": 0, "spec": "Discipline mentale", "cp": 1.2},
    "Gloaming":         {"idx": 73, "r": "Autre", "w": -3, "b": -1, "bal": 2, "spd": 1, "coo": 2, "pre": 2, "end": 1, "reg": 0, "vig": 2, "bea": 1, "spec": "Aucun", "cp": 0.8},
    "Gnoll":            {"idx": 74, "r": "Autre", "w": 6, "b": 0, "bal": -1, "spd": 1, "coo": -1, "pre": -1, "end": 1, "reg": 1, "vig": 0, "bea": -2, "spec": "Morsure + Frénésie", "cp": 0.8},
    "Goblin":           {"idx": 75, "r": "Autre", "w": -12, "b": 2, "bal": 1, "spd": 2, "coo": 1, "pre": 1, "end": 0, "reg": 0, "vig": 1, "bea": -2, "spec": "Aucun", "cp": 0},
    "Gray Orc":         {"idx": 76, "r": "Autre", "w": 3, "b": 2, "bal": 0, "spd": 1, "coo": -1, "pre": -1, "end": 2, "reg": 2, "vig": 0, "bea": -2, "spec": "Aucun", "cp": 0},
    "Grimlock":         {"idx": 77, "r": "Autre", "w": 4, "b": 4, "bal": -1, "spd": 0, "coo": -2, "pre": -2, "end": 2, "reg": 2, "vig": 0, "bea": -3, "spec": "Aveugle + odorat", "cp": 0.8},
    "Hadozee":          {"idx": 78, "r": "Autre", "w": -2, "b": 1, "bal": 2, "spd": 3, "coo": 2, "pre": 1, "end": 2, "reg": 1, "vig": 2, "bea": 1, "spec": "Grimpeur expert", "cp": 1.0},
    "Half-goblin":      {"idx": 79, "r": "Autre", "w": -8, "b": 2, "bal": 1, "spd": 2, "coo": 1, "pre": 1, "end": 1, "reg": 0, "vig": 1, "bea": -1, "spec": "Aucun", "cp": 0},
    "Harssaf":          {"idx": 80, "r": "Autre", "w": 3, "b": 1, "bal": 2, "spd": 2, "coo": 1, "pre": 1, "end": 2, "reg": 3, "vig": 2, "bea": 0, "spec": "Adaptation désert", "cp": 0.9},
    "Hobgoblin":        {"idx": 81, "r": "Autre", "w": 3, "b": 2, "bal": 0, "spd": 1, "coo": 0, "pre": 0, "end": 2, "reg": 2, "vig": 1, "bea": -1, "spec": "Discipline militaire", "cp": 0.5},
    "Ixzan":            {"idx": 82, "r": "Autre", "w": -5, "b": 2, "bal": 2, "spd": 1, "coo": 2, "pre": 2, "end": 1, "reg": 1, "vig": 2, "bea": -1, "spec": "Aucun", "cp": 1.0},
    "Juna":             {"idx": 83, "r": "Autre", "w": 0, "b": 1, "bal": 1, "spd": 2, "coo": 2, "pre": 2, "end": 2, "reg": 1, "vig": 2, "bea": 2, "spec": "Aucun", "cp": 0.8},
    "Kappa":            {"idx": 84, "r": "Autre", "w": 2, "b": 3, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 3, "reg": 3, "vig": 1, "bea": -1, "spec": "Carapace", "cp": 1.2},
    "Khala":            {"idx": 85, "r": "Autre", "w": 3, "b": 2, "bal": 1, "spd": 2, "coo": 1, "pre": 1, "end": 3, "reg": 2, "vig": 1, "bea": 0, "spec": "Aucun", "cp": 1.0},
    "Killoren":         {"idx": 86, "r": "Autre", "w": -1, "b": 1, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 2, "reg": 2, "vig": 2, "bea": 3, "spec": "Affinité nature", "cp": 1.5},
    "Koalinth":         {"idx": 87, "r": "Autre", "w": 1, "b": 2, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 2, "reg": 1, "vig": 1, "bea": -1, "spec": "Aucun", "cp": 0.5},
    "Krinth":           {"idx": 88, "r": "Autre", "w": 2, "b": 3, "bal": 0, "spd": 1, "coo": 0, "pre": 0, "end": 3, "reg": 2, "vig": 0, "bea": -2, "spec": "Résistance ombre", "cp": 1.0},
    "Kuo-toa":          {"idx": 89, "r": "Autre", "w": -4, "b": -1, "bal": 1, "spd": 1, "coo": 0, "pre": 0, "end": 1, "reg": 0, "vig": 2, "bea": -3, "spec": "Fanatisme religieux", "cp": 0.8},
    "Lightfoot":        {"idx": 90, "r": "Halfelin", "w": -13, "b": 2, "bal": 2, "spd": 2, "coo": 2, "pre": 1, "end": 1, "reg": 0, "vig": 2, "bea": 2, "spec": "Furtivité naturelle", "cp": 0},
    "Llewyrr":          {"idx": 91, "r": "Elfe", "w": -3, "b": 0, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 1, "vig": 2, "bea": 3, "spec": "Aucun", "cp": 3.0},
    "Locathah":         {"idx": 92, "r": "Autre", "w": 1, "b": 1, "bal": 1, "spd": 2, "coo": 1, "pre": 1, "end": 3, "reg": 3, "vig": 1, "bea": 0, "spec": "Respiration aquatique", "cp": 1.0},
    "Loxo":             {"idx": 94, "r": "Autre", "w": 7, "b": 5, "bal": 0, "spd": 1, "coo": -1, "pre": -1, "end": 4, "reg": 3, "vig": 0, "bea": -2, "spec": "Force colossale", "cp": 1.5},
    "Merfolk":          {"idx": 95, "r": "Autre", "w": 0, "b": 0, "bal": 1, "spd": 2, "coo": 1, "pre": 1, "end": 2, "reg": 2, "vig": 1, "bea": 2, "spec": "Respiration aquatique", "cp": 1.0},
    "Minotaur":         {"idx": 96, "r": "Autre", "w": 8, "b": 6, "bal": 0, "spd": 1, "coo": 0, "pre": -1, "end": 4, "reg": 3, "vig": 0, "bea": -2, "spec": "Charge puissante", "cp": 1.5},
    "Mongrelfolk":      {"idx": 97, "r": "Autre", "w": 2, "b": 2, "bal": 0, "spd": 1, "coo": 0, "pre": 0, "end": 2, "reg": 1, "vig": 0, "bea": -2, "spec": "Adaptation multiple", "cp": 0.8},
    "N-Tel-Quess":      {"idx": 98, "r": "Elfe", "w": -2, "b": -1, "bal": 2, "spd": 2, "coo": 3, "pre": 3, "end": 0, "reg": 1, "vig": 3, "bea": 4, "spec": "Magie ancienne", "cp": 3.5},
    "Nubari":           {"idx": 99, "r": "Humain", "w": 1, "b": 2, "bal": 0, "spd": 1, "coo": 0, "pre": 0, "end": 2, "reg": 2, "vig": 1, "bea": 0, "spec": "Aucun", "cp": 0},
    "Orc":              {"idx": 100,"r": "Demi-orc", "w": 4, "b": 2, "bal": -1, "spd": 1, "coo": -1, "pre": -1, "end": 2, "reg": 2, "vig": 0, "bea": -3, "spec": "Furie orque", "cp": 0},
    "Orog":             {"idx": 101,"r": "Demi-orc", "w": 5, "b": 4, "bal": 0, "spd": 1, "coo": -1, "pre": -1, "end": 3, "reg": 2, "vig": 0, "bea": -3, "spec": "Aucun", "cp": 0},
    "Pahari":           {"idx": 102,"r": "Autre", "w": 0, "b": 0, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 2, "reg": 2, "vig": 2, "bea": 3, "spec": "Respiration aquatique", "cp": 1.0},
    "Pangolin Katanga": {"idx": 103,"r": "Autre", "w": 3, "b": 4, "bal": 1, "spd": 0, "coo": 0, "pre": 0, "end": 4, "reg": 4, "vig": 0, "bea": -2, "spec": "Forme pangolin", "cp": 1.0},
    "Para-genasi":      {"idx": 104,"r": "Autre", "w": 1, "b": 1, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 2, "reg": 1, "vig": 1, "bea": 1, "spec": "Affinité élémentaire", "cp": 1.2},
    "Pterafolk":        {"idx": 105,"r": "Autre", "w": -2, "b": 2, "bal": 2, "spd": 3, "coo": 1, "pre": 1, "end": 2, "reg": 1, "vig": 2, "bea": 0, "spec": "Vol plané", "cp": 2.0},
    "Raptoran":         {"idx": 106,"r": "Autre", "w": -3, "b": 1, "bal": 2, "spd": 3, "coo": 2, "pre": 2, "end": 2, "reg": 1, "vig": 2, "bea": 2, "spec": "Vol naturel", "cp": 3.0},
    "Razorclaw Shifter": {"idx": 107,"r": "Autre", "w": 1, "b": 2, "bal": 1, "spd": 2, "coo": 2, "pre": 1, "end": 2, "reg": 1, "vig": 1, "bea": 0, "spec": "Transformation bestiale", "cp": 1.2},
    "Sarrukh":          {"idx": 108,"r": "Autre", "w": 5, "b": 4, "bal": 0, "spd": 1, "coo": 1, "pre": 2, "end": 3, "reg": 3, "vig": 2, "bea": -2, "spec": "Créateur de races", "cp": 2.5},
    "Saru":             {"idx": 109,"r": "Autre", "w": 3, "b": 3, "bal": 1, "spd": 2, "coo": 1, "pre": 1, "end": 3, "reg": 2, "vig": 1, "bea": -1, "spec": "Aucun", "cp": 0.8},
    "Satyr":            {"idx": 110,"r": "Autre", "w": 1, "b": 1, "bal": 2, "spd": 3, "coo": 2, "pre": 2, "end": 2, "reg": 1, "vig": 2, "bea": 3, "spec": "Charme musical", "cp": 1.5},
    "Saurial":          {"idx": 111,"r": "Autre", "w": 2, "b": 2, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 3, "reg": 3, "vig": 1, "bea": 0, "spec": "Aucun", "cp": 0.8},
    "Selûne's Children":{"idx": 112,"r": "Autre", "w": -1, "b": 0, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 2, "vig": 3, "bea": 4, "spec": "Lien lunaire", "cp": 2.0},
    "Shifter":          {"idx": 113,"r": "Autre", "w": -2, "b": -1, "bal": 2, "spd": 2, "coo": 1, "pre": 1, "end": 1, "reg": 2, "vig": 1, "bea": 0, "spec": "Transformation bestiale", "cp": 1.0},
    "Spirit Folk":      {"idx": 114,"r": "Autre", "w": -1, "b": 0, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 2, "reg": 2, "vig": 2, "bea": 3, "spec": "Esprit de la nature", "cp": 1.5},
    "Tabaxi":           {"idx": 115,"r": "Autre", "w": -4, "b": 0, "bal": 3, "spd": 4, "coo": 2, "pre": 2, "end": 1, "reg": 1, "vig": 2, "bea": 1, "spec": "Agilité féline", "cp": 1.3},
    "Talfir":           {"idx": 116,"r": "Humain", "w": 0, "b": 1, "bal": 0, "spd": 0, "coo": 1, "pre": 1, "end": 1, "reg": 0, "vig": 0, "bea": 1, "spec": "Aucun", "cp": 0},
    "Tallfellow":       {"idx": 117,"r": "Halfelin", "w": -13, "b": 1, "bal": 1, "spd": 2, "coo": 2, "pre": 2, "end": 1, "reg": 0, "vig": 2, "bea": 2, "spec": "Furtivité naturelle", "cp": 0},
    "Vodyanoi":         {"idx": 118,"r": "Autre", "w": 5, "b": 4, "bal": 1, "spd": 1, "coo": 0, "pre": 0, "end": 4, "reg": 4, "vig": 1, "bea": -2, "spec": "Aquatique", "cp": 1.2},
    "Volodni":          {"idx": 119,"r": "Autre", "w": 2, "b": 3, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 3, "reg": 3, "vig": 1, "bea": 0, "spec": "Aucun", "cp": 1.0},
    "Yuan-ti Malison":  {"idx": 120,"r": "Autre", "w": 1, "b": 2, "bal": 1, "spd": 1, "coo": 2, "pre": 2, "end": 2, "reg": 2, "vig": 2, "bea": 1, "spec": "Résistance poison", "cp": 1.8},
    "Yuan-ti Pureblood":{"idx": 121,"r": "Autre", "w": 0, "b": 1, "bal": 1, "spd": 1, "coo": 2, "pre": 2, "end": 2, "reg": 2, "vig": 2, "bea": 2, "spec": "Résistance poison", "cp": 1.5},
    "Yurian":           {"idx": 122,"r": "Autre", "w": 3, "b": 3, "bal": 0, "spd": 1, "coo": 0, "pre": 0, "end": 3, "reg": 2, "vig": 0, "bea": -2, "spec": "Aucun", "cp": 0.8},
    "Tiefling":         {"idx": 134,"r": "Autre", "w": -1, "b": 1, "bal": 0, "spd": 1, "coo": 1, "pre": 1, "end": 1, "reg": 0, "vig": 1, "bea": 1, "spec": "Magie infernale", "cp": 1.2},
    "Kenku":            {"idx": 135,"r": "Autre", "w": -8, "b": -1, "bal": 2, "spd": 2, "coo": 2, "pre": 2, "end": 0, "reg": 0, "vig": 2, "bea": -1, "spec": "Mimétisme vocal", "cp": 0.8},
    "Triton":           {"idx": 136,"r": "Autre", "w": 2, "b": 1, "bal": 1, "spd": 1, "coo": 1, "pre": 1, "end": 2, "reg": 2, "vig": 1, "bea": 1, "spec": "Respiration aquatique", "cp": 1.0},
    "Lizardfolk":       {"idx": 137,"r": "Autre", "w": 4, "b": 2, "bal": 1, "spd": 0, "coo": 0, "pre": 0, "end": 3, "reg": 3, "vig": 0, "bea": -1, "spec": "Morsure + Artisanat osseux", "cp": 1.0},
}
# ====================== PONDERATION CATEGORIES ======================
race_weights = {
    "Humain": 76,
    "Nain": 9,
    "Demi-elfe": 4,
    "Elfe": 5,
    "Halfelin": 2,
    "Gnome": 1,
    "Demi-orc": 1,
    "Autre": 2
}